18F/identity-reporting

- .eslintrc.json
- mocha-setup.ts
- typings/@observablehq/plot/index.d.ts
**Why**: Because most people ignore warnings, so we should either enforce it or drop them from the configuration.
The approach was to add `error` entries for any in [the plugin's `recommended.ts`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/configs/recommended.ts) set to `warn`.
> Set ESLint warnings to errors

- src/daily-auths-report.tsx
- typings/@observablehq/plot/index.d.ts
Using binning like this lets us take advantage of smarter axis labels
| Before | After |
| --- | -- |
| <img width="637" alt="Screen Shot 2021-08-31 at 5 21 56 PM" src="https://user-images.githubusercontent.com/458784/131592323-b856dc4d-5f7d-4697-8e29-2687330b063d.png"> | <img width="646" alt="Screen Shot 2021-08-31 at 5 21 36 PM" src="https://user-images.githubusercontent.com/458784/131592328-83eb5e7c-deb0-42a4-8813-181a7a087a92.png"> |
> Use binX because dates are continuous data

- index.html
- src/css/style.scss
- src/main.tsx
**Why**: So that the build isn't quite so slow. For additional styling, we can import just the required mixins / functions.
> Include prebuilt design system styles

- src/daily-auths-report.tsx
**Why**: so that the chart does not truncate to available
dates (aka show empty sections)
| --- | --- |
| <img width="709" alt="Screen Shot 2021-09-14 at 1 02 01 PM" src="https://user-images.githubusercontent.com/458784/133325896-e20899f5-fc29-4a62-8a65-3a1d44893c92.png"> |  <img width="706" alt="Screen Shot 2021-09-14 at 1 01 52 PM" src="https://user-images.githubusercontent.com/458784/133325926-02eb4ea7-b328-4122-8b18-a03d3d81fdb1.png"> |
> Pin chart x-axis domain

- .eslintrc.json
- src/report-filter-controls.tsx
**Why**: logically it does not make sense for the
form to contain the plot, and also the form was
limiting the width of the data table
Diff best viewed with [whitespace hidden](https://github.com/18F/identity-reporting/compare/margolis-full-width?w=1)
| --- | --- |
|  <img width="823" alt="Screen Shot 2021-09-14 at 4 56 22 PM" src="https://user-images.githubusercontent.com/458784/133349122-9d4be11a-73d4-438e-abae-147dea85bdc4.png"> | <img width="1214" alt="Screen Shot 2021-09-14 at 4 56 15 PM" src="https://user-images.githubusercontent.com/458784/133349132-fca39134-c3bb-4c66-8f29-20e9b1abf9b5.png"> |
> Move report outside of the <form> tag

- src/daily-auths-report.test.ts
- src/daily-auths-report.tsx
Based on some Slack feedback from @nickttng that there are a lot of colors by default
This turns the "unfiltered" report into one that aggregates by agency, so that selecting agency is more of a drilldown, so it changes the table as well
But now that I look at this, I think I want to keep the aggregation in the table and maybe leave out the color changing
| mode | before | after |
| --- | --- | -- |
| no agency selected | <img width="1048" alt="Screen Shot 2021-09-14 at 3 17 01 PM" src="https://user-images.githubusercontent.com/458784/133341395-3965d570-1247-41c1-a2e0-abe9804f9490.png"> |  <img width="784" alt="Screen Shot 2021-09-14 at 3 16 49 PM" src="https://user-images.githubusercontent.com/458784/133341423-cbff15b5-e462-491c-8f6e-3c0cb55c972e.png"> |
| single agency selected [no …
> Show fewer colors on main page, aggregate by agency

- src/daily-auths-report.test.ts
- src/daily-auths-report.tsx
- Add an extra significant figure
- Drop ".0" because "0.0" is redundant
For the most part d3-format's [SI prefix](https://github.com/d3/d3-format#api-reference) works, but converts "0" to "0.0" which looks really weird on graphs, especially when we only have whole-number auths in this case.
| notes | screenshot |
| --- | --- |
| before, 1 sig fig, has redundant breaks | <img width="469" alt="Screen Shot 2021-09-15 at 6 53 31 PM" src="https://user-images.githubusercontent.com/458784/133538912-14ed6c85-b30b-4225-9369-638f37c3b209.png"> |
| in progress, 2 sig figs, has "0.0" | <img width="469" alt="Screen Shot 2021-09-15 at 6 53 40 PM" src="https://user-images.githubusercontent.com/458784/133538936-61210bc7-4a1e-43af-8fff-e96800a652fa.png"> |
| final product, 2 sig figs except drops …
> Update tick formats on chart

- src/daily-auths-report.tsx
- src/main.tsx
- src/plot.tsx
- src/table.tsx
Super basic resizing of the table. It relies on preact to collect duplicate events, so maybe there is some additional debouncing we could add to simplify extra renders if we wanted... (or if we did the SVG chart rendering more directly, we could manage the elements do they wouldn't have to be torn down each time... it's fast enough for now and not causing any problems)
~**Next up**: making the table scrollable, it gets cut off when the breakpoints get too small~ (done, 3918f5a15dd77b4dd5b756aece92e1ed6e9c9a49)
| --- | --- |
| <img width="1110" alt="Screen Shot 2021-09-15 at 5 09 28 PM" src="https://user-images.githubusercontent.com/458784/133529136-b02c945a-d0f2-4e6a-83d2-9d4c7a8550db.png"> | <img width="1110" alt="Screen Shot 2021-09-15 at 5 09 44 PM" …
> Add responsive resizing of charts

- bin/generate-routes.js
- src/header.tsx
- src/main.tsx
- src/page.tsx
- src/routes/home-route.tsx
- src/routes/index.tsx
- src/routes/report-route.tsx
- typings/identity-style-guide/index.d.ts
**Why**: Vite requires static assets to be imported. It works locally only because node_modules exists in the working directly. But this folder is not created in the built environments.
> Fix images rendered by application

- src/components/daily-dropoffs-line-chart.tsx
- src/components/daily-dropoffs-report.tsx
- src/components/page.tsx
- src/components/report-filter-controls.tsx
- src/contexts/report-filter-context.tsx
- src/css/style.scss
- src/models/daily-dropoffs-report-data.test.ts
- src/models/daily-dropoffs-report-data.ts
- src/routes/index.tsx
- src/routes/report-route.tsx
(builds on #32 for organization)
Updates!
1. The table on the dropoffs reports page now filters down by agency, sorts by agency then app friendly name
2. The chart on the dropoffs report can switch between counts and percents, makes it easier to compare across apps with different scales:
| count | percent |
| --- | --- |
| <img width="907" alt="Screen Shot 2021-09-24 at 9 52 10 AM" src="https://user-images.githubusercontent.com/458784/134714143-56059143-b943-40cf-bbd4-3d58692bdd38.png"> | <img width="907" alt="Screen Shot 2021-09-24 at 9 52 03 AM" src="https://user-images.githubusercontent.com/458784/134714164-dd129a6f-f9dc-4e96-b6e6-0b8ee4099936.png"> |
> Dropoffs Report Updates

- src/components/daily-dropoffs-report.tsx
- src/components/report-filter-controls.tsx
- src/contexts/report-filter-context.tsx
- src/models/daily-dropoffs-report-data.test.ts
- src/models/daily-dropoffs-report-data.ts
I got these wrong, so this corrects that, see [notes from grace coworking](https://docs.google.com/document/d/1zGFmLGZpzuJ6ld71V0sMhIpiF01qNAg1thMvZrGkAG0/edit#)
| Old Name | New Name | Defintion                   |
| -------- | -------- | --------------------------- |
| overall  | blanket  | starts at welcome step      |
| blanket  | actual   | starts at image submit step |
I also figured the definitions could live in the form instead of the explanation accordion:
| --- | --- |
| <img width="451" alt="Screen Shot 2021-09-29 at 11 06 07 AM" src="https://user-images.githubusercontent.com/458784/135324510-399493b4-1747-4553-811b-3d2e80394f63.png"> | <img width="429" alt="Screen Shot 2021-09-29 at 11 02 25 AM" src="https://user-images.githubusercontent.com/458784/135324439- …
> Switch dropoff funnel terminology

- src/models/daily-auths-report-data.test.ts
- src/models/daily-auths-report-data.ts
- src/models/daily-dropoffs-report-data.test.ts
- Add regression spec for dropoffs report
When we have some days back, act as if they're zero rather than blow up the whole page
| --- | ---- |
| <img width="992" alt="Screen Shot 2021-09-30 at 3 26 43 PM" src="https://user-images.githubusercontent.com/458784/135538326-6406602a-5fd7-4373-a9f6-f911a53286b4.png"> | <img width="992" alt="Screen Shot 2021-09-30 at 3 26 53 PM" src="https://user-images.githubusercontent.com/458784/135538343-1bc1772f-f29f-4f0f-9c65-f7cc3703c7e3.png"> |
> Handle missing data in daily auths report

- src/components/report-filter-controls.tsx
1. probably easier to see through screenshots:
2. probably easiest to view with [whitespace changes hidden (`?w=1`)](https://github.com/18F/identity-reporting/pull/38/files?w=1)
| size | before | after |
| --- | --- | --- |
| big |<img width="789" alt="Screen Shot 2021-09-30 at 3 01 53 PM" src="https://user-images.githubusercontent.com/458784/135536289-bf2055dd-4c63-4a63-9cd7-874a3be44ed7.png"> | <img width="789" alt="Screen Shot 2021-09-30 at 3 01 59 PM" src="https://user-images.githubusercontent.com/458784/135536304-e7f398b9-ca46-40cd-98c0-a389c84f121b.png"> |
| medium | <img width="524" alt="Screen Shot 2021-09-30 at 3 03 21 PM" src="https://user-images.githubusercontent.com/458784/135536309-5d690e28-0847-4bbb-8888-e458f9e7fe2b.png"> | <img width="524" alt="Screen Shot 2021-09-30 at 3 …
> Move date controls into a 2-column layout

- index.html
- src/main.tsx
This reverts commit 06cf5f896750812c0c2c0e0ee76c9f39354f3542.
- Brings us back to aggregation across all agences (see screenshots in #45)
(Context: we had some wires crossed internally about what to show while we work on high-level data vs agency drilldown, got confirmation from @TiffanyAndrews this this OK to show)
> Bring back all-agency view

- src/components/daily-auths-report.tsx
- src/models/daily-auths-report-data.test.ts
- src/models/daily-auths-report-data.ts
- src/models/daily-dropoffs-report-data.test.ts
- src/models/daily-dropoffs-report-data.ts
- src/routes/report-route.tsx
Specs were also updated.
Core issue is that the "finish" date would be set to the beginning of the day, thus not include information that persists throughout the rest of the day.
Solution was to set the timestamp to the very end of the day - this ensures that we don't accidentally add a day to automated reports.
Originally something like 01/01/2020-01/03/2020 would only include 01/01/2020 @ 12:00AM - 01/03/2020 @ 12:00AM
This fix changes this behavior to report 01/01/2020 @ 12:00AM - 01/03/2020 @ 11:59PM as an example.
Specs had to be adjusted to recognize the change.
> Fix last day not being included in report (LG-5513)

- src/components/daily-auths-report.test.ts
- src/components/daily-auths-report.tsx
This matches the style in the dropoffs report better, and is clearer data for actual processing
| --- | --- |
| <img width="818" alt="Screen Shot 2022-06-17 at 1 20 53 PM" src="https://user-images.githubusercontent.com/458784/174396173-94049e13-88dd-49f1-8f58-08d249a68e26.png"> | <img width="818" alt="Screen Shot 2022-06-17 at 1 20 45 PM" src="https://user-images.githubusercontent.com/458784/174396187-461c5ecc-9b24-4517-88ed-d76c0b2db88c.png"> |
> Separate issuer and friendly name in daily auths CSV

- src/components/proofing-over-time-report.test.ts
- src/components/proofing-over-time-report.tsx
- src/contexts/report-filter-context.tsx
Adds the tables we know and love, with downloadability
It's the end of the day and I went a little light on the test coverage side... but if folks feel strongly, I can spend some more time adding more tests
**Note**: In some cases, the average (trendline) calculated by Plot does not match the one I calculate... 😬 
| screenshot |
| --- |
| <img width="1016" alt="Screen Shot 2022-06-28 at 4 54 44 PM" src="https://user-images.githubusercontent.com/458784/176323366-f6acff48-6b1b-4423-825b-dbfc70684775.png"> |
> Add table to proofing-over-time report (LG-6540)

- package-lock.json
reported by `npm install` fixed by `npm audit fix`
```
$ npm audit
shell-quote  <=1.7.2
Severity: critical
Improper Neutralization of Special Elements used in a Command in Shell-quote - https://github.com/advisories/GHSA-g4rg-993r-mgx7
fix available via `npm audit fix`
node_modules/shell-quote
1 critical severity vulnerability
To address all issues, run:
npm audit fix
```
> updates shell-quote to address a critical vulnerability

- src/components/proofing-over-time-report.tsx
**Why**: We care about the number of successes more than
the number of attempts
Highlighted by @porta-antiporta, thanks!
> Update proofing-over-time table to show verified count

- package.json
**Why**: [Federalist is becoming Cloud.gov Pages](https://cloud.gov/pages/federalist-migration/), and as such we'll need to update configurations accordingly.
The webhook settings have already been updated, so these changes are updating the remaining code reference to Federalist.
Resources:
- [Slack confirmation of renamed script](https://gsa-tts.slack.com/archives/C1NUUGTT5/p1664896538701049)
- [Related code](https://github.com/cloud-gov/pages-build-container/blob/508bd8f/src/steps/build.py#L186-L200)
> Migrate Federalist to Cloud.gov Pages

- bin/generate-routes.js
- src/components/header.tsx
- src/routes/all.ts
- src/routes/index.tsx
- src/routes/report-route.tsx
Used by:
- generate-routes (static node script)
- header.tsx (for the nav)
- index.tsx (to map to actual report compontent)
This is round 2 of https://github.com/18F/identity-reporting/pull/74, I opted to create a second file and use TS to require full usage, instead of trying to get cute and only have one file
> Create ALL_ROUTES constant, define all routes in one place

- README.md
Based on https://github.com/18F/identity-reporting/pull/77#pullrequestreview-1265698047
> Add some local development instructions

- .gitignore
- src/components/daily-registrations-report.test.tsx
- src/components/daily-registrations-report.tsx
- src/components/report-filter-controls.tsx
- src/contexts/report-filter-context.tsx
- src/models/daily-registrations-report-data.test.ts
- src/models/daily-registrations-report-data.ts
- src/routes/all.ts
- src/routes/index.tsx
- src/routes/report-route.tsx
- typings/@observablehq/plot/index.d.ts
Data relies on https://github.com/18F/identity-idp/pull/7674
I'm waiting for the final OK to merge this, but the resulting report will look something like (redacting numbers for now)
| cumulative | daily |
|----|----|
|  <img width="1060" alt="Screen Shot 2023-01-20 at 12 17 59 PM" src="https://user-images.githubusercontent.com/458784/213825321-c04f864c-5358-4ce3-8a86-97d2fbb383a9.png"> | <img width="941" alt="Screen Shot 2023-01-20 at 12 19 17 PM" src="https://user-images.githubusercontent.com/458784/213825340-e83d8c3a-1784-4152-bd98-9731909f71b0.png"> |
> Add Daily/Cumulative Registrations Report (LG-8679)

- src/components/daily-registrations-report.test.tsx
- src/components/daily-registrations-report.tsx
- src/models/daily-registrations-report-data.test.ts
- src/models/daily-registrations-report-data.ts
These screenshots are from `int`, the prod data will be available next week.
| description | screenshot |
|----|-----|
| graph | <img width="917" alt="Screen Shot 2023-02-03 at 2 51 18 PM" src="https://user-images.githubusercontent.com/458784/216725921-c314dfe0-6e8e-4adc-aa1c-bde1e081764d.png"> |
| table | <img width="1011" alt="Screen Shot 2023-02-03 at 2 03 34 PM" src="https://user-images.githubusercontent.com/458784/216724920-80f38b67-008a-458f-a848-ec62bb5a9c59.png"> |
> Show deletes on Daily Registrations Report

- src/components/daily-registrations-report.test.tsx
- src/components/daily-registrations-report.tsx
**Why**: makes for less horizontal scrolling when viewing a longer range of time
| --- | --- |
| <img width="1000" alt="Screen Shot 2023-02-06 at 12 53 45 PM" src="https://user-images.githubusercontent.com/458784/217083580-7ab6784a-575b-4dc2-8e15-04fb10771304.png"> | <img width="993" alt="Screen Shot 2023-02-06 at 12 53 51 PM" src="https://user-images.githubusercontent.com/458784/217083578-56e67d91-1963-4659-92ab-3a28a33141a7.png"> |
> Update daily registrations table view: one row per day

- src/components/daily-dropoffs-report.tsx
- src/components/proofing-over-time-report.tsx
**Why**: The graphs are misleading at the moment so this helps us reduce confusion.
See [slack thread for context](https://gsa-tts.slack.com/archives/C01541F40SW/p1675777991411129)
| screenshot |
| --- |
|  <img width="1045" alt="Screen Shot 2023-02-07 at 10 08 14 AM" src="https://user-images.githubusercontent.com/458784/217329960-19d2512e-362d-42b1-8351-345159f900a8.png"> |
> Hide misleading proofing reports

- src/router.test.ts
- src/router.tsx
BASE_URL in preview environments does not include a trailing slash, so avoid trimming the leading slash from the given path.
**Testing Instructions:**
1. Go to https://federalist-14721e0a-0772-4dcd-b62f-ee9d20dcc5fd.sites.pages.cloud.gov/preview/18f/identity-reporting/aduth-fix-preview-links/
2. Click a link in the navigation
3. Refresh the page
Before: 404
After: Current page is shown after refresh
> Fix full path helper for preview environments

- .mocharc.js
- package.json
**Why**: To facilitate using the Mocha command line utility directly, e.g. when running a single test file.
```
npm exec mocha src/components/daily-auths-report.test.ts
```
> Add mocharc file for common Mocha configuration

- README.md
- package.json
**Why**: Works better with our CDN
this is what we have [in our config](https://github.com/18F/identity-devops/blob/e4818146d278bdc297901cf2d17d2da6362d28c6/terraform/app/bucket-public-reporting-data.tf#L73)
> Set default port for running locally
