.eslintrc.json
.gitignore
index.html
package.json
vite.config.js

Set up project to build in Federalist

---

src/report-filter-controls.tsx

Add buttons to jump ahead/back by a week at a time

---

.eslintrc.json
package-lock.json
package.json
src/daily-auths-report.test.ts
src/daily-auths-report.tsx
src/report-filter-controls.tsx
src/report.test.ts
src/router.test.js
src/table.tsx

Related: https://github.com/18F/identity-idp/pull/5359
**Why:** So that we can use a common standard ruleset across all repositories where JavaScript is used.

Use login.gov shared ESLint configuration

---

index.html
src/daily-auths-report.test.ts
src/daily-auths-report.tsx
src/report-filter-controls.tsx
src/report.test.ts
src/report.ts
src/routes/report.tsx

- For now, no corresponding UI param
open to feedback! maybe add it in a collapsible "debug" menu or something

Add ?env= param that lets us point the web at different backends

---

src/daily-auths-report.tsx

Adds some new details
| closed | expanded |
| --- | --- |
| <img width="631" alt="Screen Shot 2021-09-15 at 1 43 20 PM" src="https://user-images.githubusercontent.com/458784/133506807-ad0bf1cd-54fb-48e2-babb-fc1f6e95dbe1.png"> | <img width="631" alt="Screen Shot 2021-09-15 at 1 43 26 PM" src="https://user-images.githubusercontent.com/458784/133506819-8076d544-17a8-4f3d-b4cd-454ae06cd0b0.png"> |
Draws inspiration from the [VA Performance Dashboard](https://www.va.gov/performance-dashboard/)

Add some details about the report, and a title

---

src/daily-auths-report.tsx

- Show exact number for bar
- Show date
- Optionally show app
| notes | screenshot |
| --- | --- |
| across all agencies: exact number + date  |  <img width="469" alt="Screen Shot 2021-09-15 at 7 40 17 PM" src="https://user-images.githubusercontent.com/458784/133656366-299fb1a4-2ea6-4c47-899e-91ed6a398404.png"> |
| agency-specific: app name + exact number + date  | <img width="469" alt="Screen Shot 2021-09-15 at 7 40 02 PM" src="https://user-images.githubusercontent.com/458784/133656452-3cd94619-6b7c-4499-ab1a-b9eebeb0a5d4.png"> |

Update title formatting

---

package-lock.json
package.json
src/context/report-filter-context.test.tsx
src/context/report-filter-context.tsx
src/daily-auths-report.test.ts
src/daily-auths-report.tsx
src/report-filter-controls.tsx
src/routes/report-route.tsx
src/url-params.ts

Previously the links were just static text but I think this makes things slightly easier to navigate.
The building of the URL is kind of a kludge.... but I couldn't find a clean way to update the form values other than this 😬

Add links from table to individual agencies

---

src/components/daily-auths-report.tsx
src/components/daily-dropoffs-report.tsx
src/hooks/resize-listener.ts

https://github.com/18F/identity-reporting/pull/31#discussion_r716919891

Remove unused ref argument for resize hook

---

package.json
robots.txt

Add a quick robots.txt to disallow everything

---

src/components/daily-auths-report.tsx

Hopefully it'll be back soon once we clear up details with partners

Disable per-issuer view on daily auths report

---

index.html
src/main.tsx

Remove pages, data.login.gov is changing directions

---

package-lock.json
package.json

Includes a font update!
| --- | --- |
| <img width="484" alt="Screen Shot 2022-01-27 at 1 53 43 PM" src="https://user-images.githubusercontent.com/458784/151452029-6c5915c7-d19c-4c3b-a35a-eb11b51d7cb7.png"> | <img width="484" alt="Screen Shot 2022-01-27 at 1 53 47 PM" src="https://user-images.githubusercontent.com/458784/151452047-80c72941-7cc7-4781-a614-975b07edca7e.png"> |

Update dependencies, update identity-style-guide

---

src/components/report-filter-controls.tsx

Update terminology for filtering

---

src/components/daily-auths-report.test.ts
src/components/daily-auths-report.tsx

Follow-up to https://github.com/18F/identity-reporting/pull/54 (because I forgot this was here too)

Update terminology in table as well

---

package-lock.json
package.json
src/components/daily-auths-report.tsx

To get the latest & greatest
Looks some of the observable plot API changes, but it seemed small

Upgrade npm packages

---

.eslintrc.json
package-lock.json
package.json
src/components/header.tsx
src/components/icon.tsx
src/components/report-filter-controls.tsx
src/components/table.tsx
src/models/daily-auths-report-data.test.ts
src/models/daily-dropoffs-report-data.test.ts

Based on https://github.com/18F/identity-reporting/pull/57#discussion_r900452102

Bump eslint packages, fix lint warnings

---

src/components/daily-auths-report.tsx
src/strings.test.ts
src/strings.ts

Fix kebab casing

---

src/components/daily-auths-report.tsx

Due to reports of inaccuracies, hiding the report for the time being

Hide daily auths report (LG-8952)

---

src/components/daily-auths-report.tsx
src/components/proofing-over-time-report.tsx

There was a miscommunication leading up to #85, this remedies that by:
- Hiding the Proofing Over Time report
- Brings back the Daily Auths Report

Hide Proofing, Not Auths

---

src/components/account-deletions-report.test.tsx
src/components/account-deletions-report.tsx
src/components/daily-dropoffs-report.tsx
src/components/table.test.tsx
src/components/table.tsx

Giving this a shot based on this comment: https://github.com/18F/identity-reporting/pull/89#discussion_r1126994693

Extract common <td> styles into components

---

package-lock.json

Updates Babel to resolve security advisories.
https://www.npmjs.com/advisories/1094349      
`npm audit` returns a clear report.

Update Babel to resolve security advisory
